# Author：gdream@126.com

use: True           # 是否使用配置文件
visual: False       # 是否表格化输出控制台
timeout: 2          # 爬取一次后的睡眠时长


redis:
  - 127.0.0.1       # ip
  - 6379            # port
  - 0               # db
  - ~               # password
  - 10              # redis-pool-max-connections


#proxy:              # 去掉注释，按规律添加代理即可
#  - 58.251.234.176
#  - 14.20.235.247
#  - 60.191.11.246


#trip:               # ddate：行程日期。route：起点->终点
#  ddate: 20200325
#  route:
#    北京: 上海
#    成都: 三亚
#    广州: 西安


